apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../../../../operators/grafana-operator/operator/overlays/v4

patches:
  - patch: |-
      - op: add
        path: /spec/targetNamespaces
        value:
          - models
    target:
      kind: OperatorGroup
      name: grafana-operator
