apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: triton-grafana

namespace: models

resources:
  - grafana-dashboard.yaml
  - grafana-instance.yaml
  - grafana-prometheus-datasource.yaml
  - grafana-route.yaml
