apiVersion: sagemaker.services.k8s.aws/v1alpha1
kind: NotebookInstanceLifecycleConfig
metadata:
  name: lifecycle-from-github
spec:
  onStart:
    # devops: base64... why?
    # security: what happens if I feed this a bin?
    # security: harder to audit
    # cat ../../sagemaker/lifecycle-from-github.sh | base64
    - content: IyEvYmluL2Jhc2gKCiMgZGVidWcKaWQKCiMgcnVuIGZyb20gcmVwbwpjdXJsIC1zTCBodHRwczovL3Jhdy5naXRodWJ1c2VyY29udGVudC5jb20vcmVkaGF0LW5hLXNzYS9kZW1vLXJvc2Etc2FnZW1ha2VyL21haW4vY29tcG9uZW50cy9kZW1vcy9zYWdlbWFrZXIvbm90ZWJvb2stbGlmZWN5Y2xlL2xpZmVjeWNsZS1vbi1zdGFydC5zaCB8IGJhc2gK
  notebookInstanceLifecycleConfigName: lifecycle-from-github
