apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  labels:
    app: triton-grafana
  name: grafana
spec:
  config:
    auth.basic:
      enabled: true
  dashboardLabelSelector:
    - matchExpressions:
        - key: app
          operator: In
          values:
            - triton-grafana
