apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: prometheus-grafanadatasource
spec:
  datasources:
  - access: proxy
    editable: true
    isDefault: true
    name: Prometheus-Triton
    type: prometheus
    url: http://prometheus-operated:9091
  name: prometheus-grafanadatasource.yaml