apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: prometheus-grafana-datasource
spec:
  datasources:
  - access: proxy
    editable: true
    isDefault: true
    name: Prometheus-Triton
    type: prometheus
    url: http://prometheus-operated:9090
  name: prometheus-grafana-datasource.yaml
