apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: model-server-s3
  name: model-server-s3
spec:
  endpoints:
  - interval: 30s
    path: /metrics
    port: 8002-tcp
  selector:
    matchLabels:
      app: model-server-s3
