apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../v5

patches:
  - target:
      kind: OperatorGroup
    patch: |-
      - op: replace
        path: /spec
        value: null
