---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus-app
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - endpoints
      - services
    verbs:
      - list
      - get
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-app
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-app
subjects:
  - kind: ServiceAccount
    name: prometheus-app
