apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: Subscription
      name: ack-route53-controller
    patch: |-
      - op: replace
        path: /spec/channel
        value: 'alpha'
  - target:
      kind: ConfigMap
      name: ack-controller-user-config
    patch: |-
      - op: replace
        path: /metadata/name
        value: 'ack-route53-user-config'
