apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../default
  - ../../instance/overlays/models

patches:
  - patch: |-
      - op: add
        path: /spec/targetNamespaces
        value:
          - models
    target:
      kind: OperatorGroup
      name: prometheus
